name: stock
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ta-lib
  - numpy=2.0.2
  - pandas=2.2.3
  - pyarrow=18.1.0
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - six=1.17.0
  - scikit-learn=1.5.2
  - scipy=1.13.1
  - joblib=1.4.2
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - statsmodels=0.14.4
  - networkx=3.4.2
  - tqdm=4.67.1
  - tabulate=0.9.0
  - jupyter=1.1.1
  - ipykernel=6.29.5
  - ipywidgets=8.1.5
  - pip
  - pip:
      - pyspark==4.0.0
      - findspark==2.0.0
      - plotly==5.24.1
      - streamlit==1.40.2
      - vnstock==3.2.0
      - requests==2.32.3
      - python-dotenv==1.0.1